source compile_cubep3m_dmnu_p3dfft_mkl.csh
source compile_dist_init_dmnu_p3dfft_mkl.csh
source compile_cic_power_dmnu_p3dfft_mkl.csh
source compile_cic_velpower_dmnu_p3dfft_mkl.csh

echo "Ready to run" 
